name: CI
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

env:
    PY_VERSION_BUILD: 3.12

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PY_VERSION_BUILD }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  pypa-build:
    name: PyPA build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PY_VERSION_BUILD }}
          cache: 'pip' # caching pip dependencies

      - run: |
          python3 -m pip install --upgrade build && python3 -m build
